### ISSUE TITLE
Integration Slack

### ISSUE THREAD

**Issue by Errorname** [zenika-open-source/FAQ#108]
Improve the slack integration with the following feature:

Typing `/faq note de frais alibeez` should show one (or more) questions linked to "note de frais alibeez

**Comment by bpetetot** [comment]
Maybe a higher issue should be : "Create a public API (with key management)"
Same needs with #107

**Comment by hgwood** [comment]
I think this can be considered done?

**Comment by Errorname** [comment]
The Slack command has been developed in the "Zenbot" project. However, since this is tightly coupled to FAQ, I am considering moving the codebase inside this project and make it "tenant-agnostic" (not only for Zenika, but other tenants as well).
