### ISSUE TITLE
Link from README does not works (e.g. https://zenika.github.io/FAQ/)

### ISSUE THREAD

**Issue by tbetous** [zenika-open-source/FAQ#185]
**Describe the bug**
Link from README does not works => https://zenika.github.io/FAQ/ because FAQ is now under zenika-open-source organization

**To Reproduce**
1. Go to README(https://github.com/zenika-open-source/FAQ)
2. Click on https://zenika.github.io/FAQ/ link

**Expected behavior**
It should redirect to https://zenika-open-source.github.io/FAQ/

**Screenshots**

**Additional context**

**Comment by Errorname** [comment]
Merged with #186
