### ISSUE TITLE
FAQ unavaillable.

### ISSUE THREAD

**Issue by Sylvain-Delafoy** [zenika-open-source/FAQ#196]
**Describe the bug**
The page load without end.

**To Reproduce**
1. Go to 'https://zenika.faq.team/'
That's it.

**Expected behavior**
The FAQ page should allow to search for an answer. In this case, nothing.

**Additional context**
Sous firefox et chromium, une requete qui semble attendre du JSON reçoit une page HTML.

With Firefox and Chromium, there is a request for a JSON that commes back with an HTML payload. Message from the console:

19:51:37,218 SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "Firefox",
      "version": "67.0.4"
    },
    "browser": {
      "name": "Firefox",
      "version": "67.0.4"
    },
    "pages": [
      {
        "startedDateTime": "2019-06-26T19:51:37.082+02:00",
        "id": "page_1",
        "pageTimings": {
          "onContentLoad": 2298,
          "onLoad": 2444
        }
      }
    ],
    "entries": [
      {
        "pageref": "page_1",
        "startedDateTime": "2019-06-26T19:51:37.082+02:00",
        "request": {
          "bodySize": 0,
          "method": "GET",
          "url": "https://zenika.faq.team/undefined/configuration",
          "httpVersion": "HTTP/1.1",
          "headers": [
********
          ],
          "cookies": [],
          "queryString": [],
          "headersSize": 396
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
          ******
            {
              "name": "Content-Type",
              "value": "text/html; charset=UTF-8"
            },
********
          ],
          "cookies": [],
          "content": {
            "mimeType": "text/html; charset=UTF-8",
            "size": 3480,
            "text": "<!doctype html><html lang=\"en\">******</body></html>"
          },
          "redirectURL": "",
          "headersSize": 332,
          "bodySize": 1893
        },
        *****
      }
    ]
  }
}

**Comment by Errorname** [comment]
Thank you for reporting this issue. The issue seems to be about a new environment variable added in commit cdb1ad6. The env variable was not added to CircleCI which then built a flawed app. (Therefore the "undefined" in the url).

I'm just added the env variable to CircleCi and re-run the workflow. This should work now.

I'm waiting your confirmation before closing this issue
