### ISSUE TITLE
Slugs with parentheses break markdown

### ISSUE THREAD

**Issue by hgwood** [zenika-open-source/FAQ#201]
**Describe the bug**

Given a question that contains a closing parenthesis (")"), then the generated slug used in the URL to that question contains the parenthesis. This URL cannot be used in a markdown link as markdown uses parens to delimit URLs in the link syntax (`[caption](link)`).

**To Reproduce**
1. Create a new question that contains a ")"
2. Copy the link to this new question
3. Answer the question, and in the answer text area, write `link to [question](<url of question>)`
4. Save the answer
5. Notice that the rendered markdown displays  `link to [question](<url of question>)`

**Expected behavior**

The rendered markdown displays  `link to question` with a hyperlink to the question on the word "question".

**Screenshots**

![image](https://user-images.githubusercontent.com/1656170/60593959-27d55300-9da4-11e9-802d-1aba5e8ce605.png)

**Comment by Errorname** [comment]
It looks like it's actually a regression on how links are parsed: a simple `[google](https://google.com)` breaks links (ex: https://zenika.faq.team/q/test-edit-question-on-prod-cjdww6g21hv72011685nqolsd)

**Comment by Errorname** [comment]
I think the problem comes from the following commit: b578fdb5bdbcf8658596ec6be4f6df33a2eae8f5 where I tried to fix another issue

**Comment by hgwood** [comment]
Thanks
