### ISSUE TITLE
Add a pre-commit hook that run Prettier

### ISSUE THREAD

**Issue by frinyvonnick** [zenika-open-source/FAQ#212]
It could be nice to have pre-commit hook that runs Prettier. It could be done easily with [Husky](https://github.com/typicode/husky)

**Comment by Amrithnath** [comment]
hey, I want to help with this one

**Comment by frinyvonnick** [comment]
Thank you @Amrithnath  for considering helping on this 🙏. I guess on server and client is the priority. Don't know if this is relevant on docs folder. What do you think of this @Errorname ?

**Comment by Errorname** [comment]
Glad to here you want to help! I agree, there is no need for a pre-commit hook on the docs

**Comment by Errorname** [comment]
Implemented in #214 by @Amrithnath. Thanks a lot 🙏
