### ISSUE TITLE
1 vues should be 1 vue.

### ISSUE THREAD

**Issue by Zenigata** [zenika-open-source/FAQ#231]
A minor typo to fix.

**Comment by louckousse** [comment]
Where is this typo?

**Comment by Zenigata** [comment]
There are several pages in FAQ that nobody viewed. Just spend a few minutes browsing it and you will see it.

**Comment by Zenigata** [comment]
Check the file `client/src/scenes/Question/scenes/Read/components/Views/Views.jsx`

**Comment by louckousse** [comment]
I take it.
