### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by bpetetot** [zenika-open-source/FAQ#235]
Add a code of conduct for the project
Add it in the `.github` file

How to add a code of conduct:
https://help.github.com/en/articles/adding-a-code-of-conduct-to-your-project

Example of code of conduct:
https://www.contributor-covenant.org
https://github.com/bpetetot/conference-hall/blob/master/docs/CODE_OF_CONDUCT.md

**Comment by Yexan** [comment]
I can do it if you want

**Comment by Yexan** [comment]
Can you provide me an email address to put in the code of conduct to contact you ?
Thanks :)

**Comment by Errorname** [comment]
Hi, thank you for your interest in this issue 😃 

You can use this email: thibaud.courtoison@zenika.com

**Comment by Yexan** [comment]
Oh sweet, someone give opensource@zenika.com 

I made the PR here https://github.com/zenika-open-source/FAQ/pull/236 
Is it ok for you or should I change it ?

**Comment by Errorname** [comment]
That's even better! :D
