### ISSUE TITLE
Wrong link in Slack when creating a Question

### ISSUE THREAD

**Issue by jlandure** [zenika-open-source/FAQ#248]
**Describe the bug**
The link generated by the bot goes to the wrong instance of FAQ: `zenika.faq.team` instead of `gdgnantes.faq.team`
Perhaps something in the `ctx` is wrong: https://github.com/zenika-open-source/FAQ/blob/master/server/src/integrations/slack.js#L15

**To Reproduce**
1. Go to `gdgnantes.faq.team`
2. Create a question
3. Go to Slack
4. Click on the msg generated by the `FAQ bot`

**Expected behavior**
A Link to `gdgnantes.faq.team` instead of `http://zenika.faq.team`

**Comment by Errorname** [comment]
Thanks for the issue! 🙏 
This was a wrongly configured env variable in Circle CI. This is now fixed.

**Comment by jlandure** [comment]
Thanks for the job! 🎉
