### ISSUE TITLE
Message d'erreur GraphQL lors de la création d'une question

### ISSUE THREAD

**Issue by Seboran** [zenika-open-source/FAQ#364]
**Describe the bug**
Lors ce que je crée une question j'ai le message d'erreur suivant :

`GraphQL error: Variable '$_v0_data' expected value of type 'ZNodeCreateInput!' but got: {"question":{"create":{"title":"Comment se connecter à la télé de la salle RAM ?","slug":"comment-se-connecter-a-la-tele-de-la-salle-ram","user":{"connect":{"id":"clex1oqk84acc0847u0iih5tw"}}}},"flags":{"create":[{"type":"unanswered","user":{"connect":{"id":"clex1oqk84acc0847u0iih5tw"}}}]},"tags":{"create":[{"label":{"connect":{"id":"ck07vjrpj003t0845svyp69zx"}},"user":{"connect":{"id":"clex1oqk84acc0847u0iih5tw"}}},{"label":{"connect":{"id":"cl2kgkatl066v0b16ocbbl2qe"}},"user":{"connect":{"id":"clex1oqk84acc0847u0iih5tw"}}}]}}. Reason: 'question.create.language' Expected non-null value, found null. (line 1, column 11): mutation ($_v0_data: ZNodeCreateInput!) { ^

`

**To Reproduce**
Créer une question et écrire : "Comment se connecter à la télé de la salle RAM ?"

**Expected behavior**
Pouvoir poser la question

**Screenshots**

**Additional context**
J'ai essayé sur le navigateur Arc et Firefox

**Comment by hgwood** [comment]
Fixed :)
